### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Gribouillis** [domdfcoding/PySetWacom#1]
## Description

PySetWacom command fails at startup with IndexError

## Steps to Reproduce

   1. Use kubuntu 16.04, install python 3.8.3 with pyenv
   2. Install wxpython from https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/
   3. Install pysetwacom with pip and various libraries until it works
   4. type the command pysetwacom

## Actual result:

The actual result is a python traceback indicating an IndexError

    λ pysetwacom
    Applying xmodmap overrides
    My PID is: 4732
    Traceback (most recent call last):
      File "/home/eric/.pyenv/versions/3.8.3/bin/pysetwacom", line 10, in <module>
    sys.exit(main())
      File "/home/eric/.pyenv/versions/3.8.3/lib/python3.8/site-packages/PySetWacom/__main__.py", line 53, in main
    TrayIcon()
      File "/home/eric/.pyenv/versions/3.8.3/lib/python3.8/site-packages/PySetWacom/tray_icon.py", line 48, in __init__
    self.build_menu()
      File "/home/eric/.pyenv/versions/3.8.3/lib/python3.8/site-packages/PySetWacom/tray_icon.py", line 119, in build_menu
    self.build_profiles_menu()
      File "/home/eric/.pyenv/versions/3.8.3/lib/python3.8/site-packages/PySetWacom/tray_icon.py", line 110, in build_profiles_menu
    first_radioitem = self._profiles_submenu.AppendRadioItem(-1, self.profiles[0], None)
    IndexError: list index out of range

## Expected result:

A graphical interface running.

## Version

  * Operating System: Kubuntu 16.04
  * Python: 3.8.3
  * PySetWacom: 0.1.6

## Installation source

pip

**Comment by domdfcoding** [comment]
Hi @Gribouillis,

Doh! I see the problem. This should be fixed in Version 0.1.8 on PyPI. Can you give that version a try, and let me know if you run into any further problems?

Also, I'd appreciate any feedback you can give on the installation instructions.

Many thanks 🙂
